# Specially prepared build & release workflow for this forked repository.

name: Build release assets

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Enable uv cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync Python deps
        run: uv sync --all-extras

      - name: Build frontend assets
        run: |
          uv run npm install || echo "Ignore npm install error"
          uv run npm run build

      - name: Build Python distributions
        run: uv build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
            files: dist/*